language: node_js
node_js:
  - "5.4"
addons:
  apt:
    packages:
      - p7zip-full
cache:
  directories:
    - data
script:
  - make -j8 travis
after_success:
  - if [[ $TRAVIS_REPO_SLUG != alerque/stack-verse-mapper ]]; then exit; fi
  - if [[ $TRAVIS_BRANCH != travis ]]; then exit; fi
  - if [[ $TRAVIS_PULL_REQUEST != false ]]; then exit; fi
  - make -j8 travis-deploy
